### PR TITLE
notebook to copy dataset and create manifest

### PR DESCRIPTION
**Pull request by rpwagner**
This notebook shows how to use Globus to copy a dataset from one guest collection to another. It also generates the manifest and uploads it to the destination. 

We can save the manifest locally to help build the dataset landing pages.

Needs more narrative text and maybe some diagrams, unless those end up in the presentation.

### CODE REVIEW

**Comment by rpwagner** [comment]
@zonca should this be in the [cheapandfair-gateways-2024](https://github.com/cheapandfair/cheapandfair-gateways-2024) repo instead?

**Comment by zonca** [comment]
Exactly

**Comment by zonca** [comment]
See notebook 3, I assume this template is cloned in a subfolder

**Comment by rpwagner** [comment]
Got it, I'll do a PR to that repo.

**Comment by zonca** [comment]
is this a replacement for https://github.com/cheapandfair/cheapandfair-template/blob/main/0_create_manifest.py?
I am worried that it is more complicated and needs to be customized to the dataset

**Comment by rpwagner** [comment]
Yes, it does replace that script or is alternate way to do it. The current script requires that the user has access to the file system where datasets are. The steps in the notebook generate the manifest after the Globus transfer, so the user never needs direct access to the files.

For the tutorial, I was thinking we don't want the students copying all the files to JupyterHub server unless there's a need to.

**Comment by rpwagner** [comment]
Also, I can covert the notebook to a script that takes command line arguments like which dataset to copy.

**Comment by zonca** [comment]
ok, yes, let's go with a script,
let's keep also the other script there, it might be easier in some cases.
You can read details about the endpoint from ENDPOINT.sh, which is created by https://github.com/cheapandfair/cheapandfair-gateways-2024/blob/main/2_globus.ipynb

**Pull request closed without merging**
